### ISSUE TITLE
I would like to add some free and paid courses in the readme 

### ISSUE THREAD

**Issue by akshitagupta15june** [AccessibleForAll/Resources#19]
please assign

**Comment by EmmaDawsonDev** [comment]
Sure, go ahead :)

**Comment by akshitagupta15june** [comment]
Can u also add a "hacktoberfest" label tag in your project
So my contribution will be counted in hacktoberfest

**Comment by EmmaDawsonDev** [comment]
This is technically a collection repo and as they are not in line with Hacktoberfest that's why I haven't added the hacktoberfest label. I don't want to open the repo up for people adding low quality links just for a hacktoberfest t-shirt. I hope you understand. 

I have a couple of other repos that have the hacktoberfest label if you wish to contribute to those. I'll be listing more issues over the coming days.

**Comment by akshitagupta15june** [comment]
No issue I will contribute in this💜

**Comment by md-abid-hussain** [comment]
Can i work on this issue?
The assignee doesn't seems making any progress

**Comment by EmmaDawsonDev** [comment]
Sure, if you have some useful links then go ahead and add them
